{
  "headers": {
    "client_id": "18361836",
    "client_secret": "aKHDJ871",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.25.0",
    "accept": "*/*",
    "postman-token": "a9b6d1a9-7f9b-406e-a1cf-84afeedcde97",
    "host": "localhost:8082",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "1700"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "https",
  "queryParams": {},
  "requestUri": "/api/generateCoupon",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/generateCoupon",
  "listenerPath": "/api/*",
  "relativePath": "/api/generateCoupon",
  "localAddress": "/127.0.0.1:8082",
  "uriParams": {},
  "rawRequestUri": "/api/generateCoupon",
  "rawRequestPath": "/api/generateCoupon",
  "remoteAddress": "/127.0.0.1:52208",
  "requestPath": "/api/generateCoupon"
}