{
  "headers": {
    "client_id": "18361836",
    "client_secret": "aKHDJ871",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.25.0",
    "accept": "*/*",
    "postman-token": "96f35df3-4fdd-4f48-81d3-7022ea870114",
    "host": "localhost:8082",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "1700"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "https",
  "queryParams": {},
  "requestUri": "/api/generateCoupon",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/generateCoupon",
  "listenerPath": "/api/*",
  "relativePath": "/api/generateCoupon",
  "localAddress": "/127.0.0.1:8082",
  "uriParams": {},
  "rawRequestUri": "/api/generateCoupon",
  "rawRequestPath": "/api/generateCoupon",
  "remoteAddress": "/127.0.0.1:56937",
  "requestPath": "/api/generateCoupon"
}